// This file is automatically generated at compile-time to include a user created header file.
#define UE_DIRECT_HEADER_COMPILE 1
#define __COMPILING_AMyActor
#include "C:/Unreal_Projects/test1/Source/test1/Public/AMyActor.h"
